/**
 * All user-facing interface text, in plain English, in one file
 * (docs/SCOPE.md: no i18n framework). Level text lives in content/ JSON.
 *
 * Ownership: the UI workstream owns every section except `classroom`
 * (Classroom workstream). Add keys to your own section only.
 */
export const STRINGS = {
  common: {
    appName: 'Git Quest',
    tagline: 'Learn git and GitHub by helping a small team ship a festival website.',
    loading: 'Loading…',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    back: 'Back',
    next: 'Next',
    continue: 'Continue',
    home: 'Home',
    backHome: 'Back to the map',
    starsOf: '{count} of {max} stars',
    starsTotal: '{count} stars',
    stars: 'Stars',
    level: 'Level {id}',
    chapter: 'Chapter {n}',
    boss: 'Boss level',
    skipToContent: 'Skip to the main content',
    notFoundTitle: 'Page not found',
    notFoundBody: 'There is nothing at "{path}". Head back to the map to keep playing.',
  },
  profile: {
    title: 'Welcome to Lantern Labs!',
    intro: 'You are the new intern on a tiny team building the website for the Riverside Lantern Festival. What should the team call you?',
    nameLabel: 'Your name',
    nameHint: 'Used in the story and for your simulated commits. It never leaves this browser.',
    classCodeLabel: 'Class code (optional)',
    classCodeHint: 'If your teacher gave you a code, type it here. You can add it later in Settings.',
    save: 'Start playing',
    nameRequired: 'Please type a name (a nickname is fine).',
    handlePreview: 'Your simulated GitHub name will be "{handle}".',
  },
  home: {
    welcomeBack: 'Welcome back, {name}!',
    welcome: 'Welcome, {name}!',
    storyTitle: 'The story so far',
    story:
      'Lantern Labs is a tiny team building the website for the Riverside Lantern Festival. Ada, the mentor, will show you each new idea. Sam moves fast and sometimes edits the same lines as you. Priya reviews your work. Every skill you learn is one the team needs right now.',
    continue: 'Continue: {id} {title}',
    startFirst: 'Start the first level',
    allDone: 'You finished every level. Try the sandbox, or replay a boss level for three stars.',
    mapTitle: 'Chapter map',
    mapIntro: 'Levels are suggested in order, but nothing is locked. Jump to any level you like.',
    levelsDone: '{done} of {total} levels done',
    suggested: 'Suggested next',
    notPlayed: 'Not played yet',
    completed: 'Completed',
    notAvailable: 'Not available in this build',
    badgesTitle: 'Badges',
    badgesIntro: 'Badges are just for fun. They never lock or unlock levels.',
    earned: 'Earned',
    notEarned: 'Not earned yet',
    sandboxTitle: 'Sandbox',
    sandboxBody: 'A free playground with the full world view. Try anything.',
    glossaryTitle: 'Glossary',
    glossaryBody: 'Every term and recap you have unlocked.',
    settingsTitle: 'Settings',
    settingsBody: 'Theme, text size, motion and your progress file.',
    exportTitle: 'Hand in your progress',
    exportBody: 'Download your progress file and submit it to your teacher. Two files are saved: a .gitquest.json file and a .csv table.',
    professorLink: 'For teachers: Professor dashboard',
  },
  badges: {
    'first-level': { name: 'First steps', description: 'Finish your first level.' },
    chapter: { name: 'Chapter {n} complete', description: 'Finish every level in chapter {n}: {title}.' },
    stars: { name: '{count} stars', description: 'Collect {count} stars.' },
    'all-stars': { name: 'Lantern bright', description: 'Get three stars on every level.' },
    sandbox: { name: 'Explorer', description: 'Spend {count} minutes in the sandbox.' },
    newBadge: 'New badge: {name}',
  },
  topBar: {
    levelLabel: '{id} · {title}',
    sandboxLabel: 'Sandbox · {preset}',
    rewind: 'Rewind',
    rewindHelp: 'Undo your last change (free, no star cost)',
    restart: 'Restart',
    restartHelp: 'Start this level again from the beginning',
    glossary: 'Glossary',
    sandbox: 'Sandbox',
    settings: 'Settings',
    home: 'Home',
    totalStars: 'Total stars: {count}',
    mainNav: 'Game controls',
  },
  mission: {
    title: 'Mission',
    sandboxTitle: 'Sandbox',
    sandboxIntro: 'This is a free playground. Nothing here is graded, and you can try any command.',
    sandboxPreset: 'Starting point: {preset}',
    sandboxStartOver: 'Start over',
    sandboxChange: 'Choose another starting point',
    storyTitle: 'Story',
    storyNext: 'Next',
    storyStart: 'Let’s go',
    storyOf: 'Line {n} of {total}',
    dialogueTitle: 'Messages',
    goalsTitle: 'Goal',
    goalDone: 'Done',
    goalTodo: 'Not done yet',
    goalAnnounce: 'Goal done: {text}',
    allGoalsAnnounce: 'All goals done. Level complete!',
    questionsTitle: 'Check your understanding',
    questionCorrect: 'Correct!',
    questionWrong: 'Not quite. Try again.',
    hintsTitle: 'Hints',
    hintButton: 'Show a hint',
    hintButtonNext: 'Show the next hint',
    hintsAllShown: 'All hints shown',
    hintCostNote: 'The first hint is free. Hints 2 and 3 cost one star each.',
    hintTier: 'Hint {tier}',
    hintTierNames: ['A nudge', 'The idea', 'The exact command'],
    actionsTitle: 'Try it',
    actionsIntro: 'Each button types its command into the terminal for you.',
    parInfo: 'Commands used: {used} (par {par})',
    parInfoNoPar: 'Commands used: {used}',
    parHelp: 'Par is the number of changing commands in a three-star solution. Looking around (status, log, ls) is free.',
    projected: 'If you finish now: {stars}',
    cheatTitle: 'Command cheat card',
    cheatEmpty: 'Commands you learn will appear here.',
    demoTitle: 'Watch Ada',
    demoRunning: 'Ada is showing you how it works…',
    demoSkip: 'Skip the demo',
    completeBanner: 'Level complete!',
    showResults: 'Show results',
  },
  speakers: {
    Ada: 'Ada',
    Sam: 'Sam',
    Priya: 'Priya',
    Leo: 'Leo',
    Narrator: 'Narrator',
    You: 'You',
  },
  predict: {
    title: 'Predict',
    intro: 'Before this command runs: which picture will you get?',
    command: 'Command: {command}',
    correct: 'Yes! Good prediction.',
    wrong: 'Not this time, and that is fine. Watch what happens.',
    answerWas: 'The answer is: {answer}',
    continue: 'Run the command',
    choice: 'Choice {n}',
  },
  win: {
    title: 'Level complete!',
    starsLine: 'You earned {stars}.',
    recapTitle: 'What you learned',
    glossaryAdded: 'Added to your glossary',
    statsCommands: 'Commands: {used} (par {par})',
    statsCommandsNoPar: 'Commands: {used}',
    statsHints: 'Hints used: {count}',
    statsTime: 'Time: {time}',
    starRule: 'Three stars: no hint 2 or 3, and within par.',
    next: 'Next level',
    nextNamed: 'Next: {id} {title}',
    replay: 'Replay',
    home: 'Back to the map',
    close: 'Look around first',
    lastLevel: 'That was the last level. Well done!',
  },
  gitEditor: {
    title: 'Git opened an editor',
    intro: '{command} is waiting for you to write a message. Lines starting with # are ignored.',
    file: 'File: {file}',
    textLabel: 'Message',
    save: 'Save and close',
    abort: 'Close without saving',
    waiting: 'hint: Waiting for your editor to close the file... ',
  },
  world: {
    title: 'World view',
    tabWorld: 'World view',
    tabHub: 'GitHub website',
    tabsLabel: 'Choose a view',
    working: 'Working folder',
    workingHelp: 'The files on your laptop, as you see them in the editor.',
    staging: 'Staging area',
    stagingHelp: 'Changes you picked for the next commit.',
    repository: 'Repository',
    repositoryHelp: 'Saved snapshots (commits), newest at the top.',
    remote: 'GitHub (remote)',
    remoteHelp: 'The copy of the project on the simulated GitHub.',
    folder: 'Your folders',
    folderHelp: 'Everything in your home folder. The pin shows where you are.',
    youAreIn: 'You are in {path}',
    youAreHere: 'You are here',
    noRepo: 'No repository yet.',
    noRepoHint: 'Run git init to start tracking this folder.',
    outsideRepo: 'You are outside the repository {path}.',
    emptyFolder: 'This folder is empty.',
    stagingEmpty: 'Nothing staged.',
    stagingEmptyHint: 'git add copies changes here.',
    stagingUnchanged: '+ {count} unchanged files (same as the last commit)',
    stagingUnchangedOne: '+ 1 unchanged file (same as the last commit)',
    noCommits: 'No commits yet.',
    noCommitsHint: 'git commit saves the staging area as a snapshot.',
    inProgressMerge: 'A merge is in progress.',
    inProgressRevert: 'A revert is in progress.',
    showLost: 'Show commits only the reflog remembers ({count})',
    truncated: 'Showing the newest {count} commits.',
    remoteNone: 'No GitHub repository yet.',
    remoteNotConnected: 'Not connected to your laptop yet (no remote).',
    remoteName: 'Remote: {name}',
    remoteUrl: 'URL: {url}',
    remoteMissing: 'The remote {name} points to {url}, which does not exist on GitHub.',
    remoteEmpty: 'This GitHub repository has no commits yet.',
    remotesLabel: 'Remotes',
    badges: {
      untracked: 'untracked',
      modified: 'modified',
      deleted: 'deleted',
      conflict: 'conflict',
      staged: 'staged',
      ignored: 'ignored',
    },
    kinds: {
      added: 'new file',
      modified: 'modified',
      deleted: 'deleted',
      renamed: 'renamed',
      typechange: 'type changed',
      conflict: 'conflict',
    },
    renamedFrom: 'from {from}',
    openInEditor: 'Open {path} in the editor',
    captions: {
      stage: 'git add copies the file into the staging area',
      unstage: 'The change leaves the staging area (your edit stays in the working folder)',
      remove: 'The file is marked for deletion in the staging area',
      commit: 'The staging area becomes a new commit in the repository',
      checkout: 'Git updates the files in your working folder',
      push: 'Your commits upload to GitHub',
      fetch: 'New commits download from GitHub',
      clone: 'A full copy downloads from GitHub',
      rejected: 'GitHub refused the push',
      conflict: 'Conflict! Both sides changed the same lines',
    },
  },
  graph: {
    label: 'Commit graph of {where}',
    remoteLabel: 'Commit graph of {where} on GitHub',
    youAreHere: 'You are here',
    youAreHereDetached: 'You are here (detached)',
    headShort: 'HEAD',
    commitLabel: 'Commit {id}: {subject}',
    mergeCommitLabel: 'Merge commit {id}: {subject}',
    lostLabel: 'Commit {id} (only in the reflog): {subject}',
  },
  graphDesc: {
    empty: 'No commits yet.',
    emptyOnBranch: 'No commits yet. You are on branch {branch}, which has no commits.',
    countOne: '1 commit.',
    count: '{count} commits.',
    mergesOne: '1 merge commit.',
    merges: '{count} merge commits.',
    headOnBranch: 'You are on branch {branch}, at {commit}.',
    headOnUnborn: 'You are on branch {branch}, which has no commits yet.',
    headDetached: 'HEAD is detached at {commit}.',
    branch: 'Branch {name} points to {commit}.',
    remote: 'Remote-tracking branch {name} points to {commit}.',
    tag: 'Tag {name} points to {commit}.',
    commitRef: '"{subject}" ({id})',
    commitRefPlain: 'commit {id}',
    more: 'And {count} more labels.',
    truncated: 'Only the newest {count} commits are shown.',
  },
  sheet: {
    where: 'In {where}',
    shortId: 'Short id',
    fullId: 'Full id',
    author: 'Author',
    date: 'Date',
    parents: 'Parents',
    noParents: 'None: this is the first commit.',
    mergeNote: 'Two parents: this merge commit joins two lines of history.',
    labels: 'Labels here',
    message: 'Full message',
    snapshot: 'Snapshot: {count} files',
    snapshotOne: 'Snapshot: 1 file',
    snapshotNote: 'A commit stores every file as it was, not just the changes.',
    missingTitle: 'Commit not found',
    missing: 'This commit is not in the repository any more.',
    noMessage: '(no message)',
    laptop: 'your laptop',
  },
  picture: {
    empty: '(empty)',
    boxesDescription: 'Working folder: {working}. Staging area: {staging}. Repository: {repository}.',
  },
  files: {
    title: 'Files',
    rootLabel: 'Folder: {path}',
    newFile: 'New file',
    newFileName: 'File name',
    newFileHint: 'For example notes.txt or css/site.css',
    create: 'Create',
    newFileInvalid: 'Type a file name, like notes.txt.',
    noFiles: 'No files here yet.',
    pickFile: 'Pick a file on the left to open it here.',
    editorLabel: 'Editing {path}',
    save: 'Save',
    saveShortcut: 'Save (Ctrl+S)',
    saved: 'Saved',
    unsaved: 'Unsaved changes',
    closeFile: 'Close file',
    changedOnDisk: 'This file changed outside the editor.',
    reload: 'Load the new version',
    deletedOnDisk: 'This file no longer exists. Saving will create it again.',
    conflictBanner: 'This file has {count} conflict(s). Keep the lines you want, delete the marker lines (<<<<<<<, =======, >>>>>>>), then save.',
    treeLabel: 'Files in {path}',
    folder: 'folder',
  },
  terminal: {
    title: 'Terminal',
    label: 'Terminal. Type a command and press Enter.',
    adaPrefix: 'Ada:',
    machinesLabel: 'Machines',
    machineTab: '{label}',
    interrupted: '^C',
    focusHelp: 'Tab completes commands. Press Ctrl+Alt+1, 2 or 3 to move to another panel.',
    rewound: 'Rewound one step.',
  },
  glossary: {
    title: 'Glossary',
    intro: 'Every term and recap you have unlocked so far.',
    search: 'Search the glossary',
    searchPlaceholder: 'Search, e.g. commit',
    termsTitle: 'Terms',
    recapsTitle: 'What you learned in each level',
    empty: 'Nothing here yet. Finish levels to fill your glossary.',
    noMatch: 'No matches for "{query}".',
    locked: '{count} more terms unlock as you play.',
    lockedOne: '1 more term unlocks as you play.',
    command: 'Command: {command}',
    related: 'Related: {terms}',
    fromLevel: 'Level {id}',
  },
  settings: {
    title: 'Settings',
    appearance: 'Appearance',
    theme: 'Theme',
    themes: { system: 'Match my computer', light: 'Light', dark: 'Dark' },
    fontScale: 'Text size',
    fontScales: ['Small', 'Normal', 'Large', 'Extra large'],
    motion: 'Motion',
    animationSpeed: 'Animation speed',
    speeds: { slow: 'Slow', normal: 'Normal', fast: 'Fast' },
    reducedMotion: 'Reduce motion (no gliding animations)',
    accessibility: 'Accessibility',
    screenReader: 'Screen reader mode for the terminal',
    screenReaderHelp: 'Makes terminal output readable by screen readers.',
    profile: 'Your profile',
    profileName: 'Name',
    profileClassCode: 'Class code',
    profileSave: 'Save profile',
    profileSaved: 'Profile saved.',
    profileHandle: 'Simulated GitHub name: {handle}',
    progress: 'Your progress',
    progressHelp: 'Progress is saved in this browser only. Export it to hand it in or move it to another computer.',
    export: 'Export my progress',
    exported: 'Downloaded {json} and {csv}.',
    import: 'Import a progress file',
    importHelp: 'Replaces the progress in this browser with the file you choose.',
    importOk: 'Progress imported.',
    importFailed: 'Could not import that file: {error}',
    reset: 'Reset all progress',
    resetConfirmTitle: 'Reset all progress?',
    resetConfirmBody: 'This deletes your stars, badges and glossary in this browser. Export your progress first if you want to keep it.',
    resetConfirm: 'Yes, reset everything',
    resetDone: 'All progress was reset.',
    shortcuts: 'Keyboard shortcuts',
  },
  shortcuts: [
    { keys: 'Ctrl+Alt+1', action: 'Go to the mission panel' },
    { keys: 'Ctrl+Alt+2', action: 'Go to the world view' },
    { keys: 'Ctrl+Alt+3', action: 'Go to the files and editor' },
    { keys: 'Ctrl+Alt+4', action: 'Go to the terminal' },
    { keys: 'Ctrl+Alt+5', action: 'Switch between the world view and the GitHub website' },
    { keys: 'Ctrl+Alt+H', action: 'Show the next hint' },
    { keys: 'Ctrl+Alt+Z', action: 'Rewind one step' },
    { keys: 'Esc', action: 'Close the open dialog or panel' },
    { keys: 'Tab (in the terminal)', action: 'Complete a command or file name' },
    { keys: 'Up / Down (in the terminal)', action: 'Previous and next commands' },
    { keys: 'Ctrl+C (in the terminal)', action: 'Cancel the line you are typing' },
    { keys: 'Ctrl+L (in the terminal)', action: 'Clear the screen' },
    { keys: 'Ctrl+S (in the editor)', action: 'Save the file' },
  ],
  sandbox: {
    title: 'Sandbox',
    intro: 'Pick a starting point. Nothing in the sandbox is graded, so experiment freely.',
    presets: {
      empty: { name: 'Empty laptop', description: 'An empty home folder. Make a folder, run git init and build from scratch.' },
      festival: { name: 'Festival project', description: 'The festival website with a few commits and a branch, ready to explore.' },
      'festival-with-remote': {
        name: 'Festival project with GitHub',
        description: 'The festival website connected to a repository on the simulated GitHub, for push, fetch and pull.',
      },
    },
    start: 'Start',
  },
  play: {
    levelMissingTitle: 'Level not found',
    levelMissing: 'There is no level "{id}" in this build.',
    startFailedTitle: 'This level could not start',
    startFailed: 'Something went wrong while setting up the level: {error}',
    tryAgain: 'Try again',
  },
  dev: {
    title: 'Developer preview',
    intro: 'A mock session for working on the interface. Only available in development builds.',
    variants: { full: 'Full level (chapter 6)', chapter0: 'Chapter 0 (no repository)', conflict: 'Merge conflict', editor: 'Git editor open', sandbox: 'Sandbox' },
  },
  time: {
    seconds: '{s}s',
    minutes: '{m}m {s}s',
  },
  classroom: {
    exportProgress: 'Export my progress',
    /** Why importFile refused a file ({version} and {detail} are filled in). */
    importError: {
      empty: 'This file is empty. Export your progress again and use the new file.',
      tooLarge: 'This file is too big to be a Git Quest progress file.',
      notJson: 'This is not a Git Quest progress file. Progress files end in .gitquest.json.',
      notProgress: 'This is not a Git Quest progress file. Progress files end in .gitquest.json.',
      newerVersion: 'This file comes from a newer version of Git Quest (format {version}). Reload the game to get the newest version, then try again.',
      olderVersion: 'This file comes from an old version of Git Quest (format {version}). It can no longer be loaded.',
      damaged: 'This Git Quest file is damaged (problem at "{detail}"). Export your progress again and use the new file.',
      checksum: 'This file was changed after it was exported, so it cannot be loaded. Export your progress again and use the new file.',
    },
    /** Labels in the exported CSV file. */
    csv: {
      name: 'Name',
      handle: 'Handle',
      classCode: 'Class code',
      exportedAt: 'Exported at',
      levelId: 'Level',
      title: 'Title',
      completed: 'Completed',
      stars: 'Stars',
      attempts: 'Attempts',
      completions: 'Completions',
      timeSpentSec: 'Time spent (seconds)',
      hintsUsed: 'Hints used',
      maxHintTier: 'Highest hint tier',
      errors: 'Errors',
      firstCompletedAt: 'First completed at',
      yes: 'yes',
      no: 'no',
    },
    /** The page for professors (#/professor): how to collect and read exported files. */
    professorPage: {
      title: 'For professors: collecting progress',
      lead: 'Git Quest has no server. Each student’s progress stays in their own browser until they export it and send it to you.',
      collectTitle: '1. Collect the files',
      collectSteps: [
        'Give students the game link and a class code. They type both on first launch.',
        'When work is due, students press “Export my progress”. The game saves a .csv file and a .gitquest.json file.',
        'Students upload the files to an assignment in your learning platform, such as Canvas, Moodle or Google Classroom.',
      ],
      readTitle: '2. Read the CSV file',
      readSteps: [
        'Open it in Excel, Google Sheets or LibreOffice.',
        'The first rows show the student’s name, handle, class code and the export time.',
        'Then there is one row per level, in game order: completed, stars, attempts, time, hints and errors.',
        'Boss level titles start with “Boss:”. They are the best sign of what a student can do on their own.',
      ],
      jsonTitle: '3. Keep the JSON file',
      jsonSteps: [
        'The .gitquest.json file is the full record. It ends with a checksum that no longer matches if someone edits the file by hand.',
        'The game refuses to import an edited file. To check one, open the game in a private browser window and import it there.',
        'A student who changes computers can import their own file to continue where they stopped.',
      ],
      privacyTitle: 'Privacy',
      privacyBody:
        'A progress file holds only a display name, a class code and level results. Nothing is sent to any server. Check your university’s rules (for example FERPA or GDPR) before you collect files.',
      guide: 'The Professor Guide (docs/PROFESSOR_GUIDE.md in the Git Quest repository) has a 6-week plan, grading ideas and a final-project brief.',
      backLink: 'Back to the game',
    },
  },
} as const;

/** Replace {name} placeholders in a template: fmt('Hi {name}', { name: 'Ada' }). */
export function fmt(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (whole, key: string) => (key in vars ? String(vars[key]) : whole));
}
